### ISSUE TITLE
jg2 can't open repo folders

### ISSUE THREAD

**Issue by MNR85** [warmcat/gitohashi#2]
Hi. After running gitohashi there was an error in opening.
This error happens when new http request (localhost/git) in browser
```
 ++ [wsisrv|2|h2] (2)
__jg2_conf_gitolite_admin_head: can't open /var/lib/gitolite3/repositories/gitolite-admin.git
 -- [wsisrv|2|h2] (1)   963us     
lwsac_use_cached_file_end: html refcount zero on entry
```
I runned this cmd, but no effect
```
sudo chmod -R a+rwX /var/lib/gitolite3
```
And as result of this error, no repo is visible in homepage.
More info:
- created "git"  sudo user with uid and gid 48 (it seems it has to be 48 only) and passed public key to gitolite3
- on debian 10
My steps to install
```
# install deps
sudo apt update && sudo apt install build-essential git psmisc cmake libgit2-27 libgit2-dev libarchive13 libarchive-dev libmount-dev libsqlite3-dev libssl-dev openssl libssl1.1

#install lws
git clone https://xxx/libwebsocket.git && cd libwebsocket && mkdir build && cd build && cmake .. -DLWS_FOR_GITOHASHI=1 && make && sudo make install && sudo ldconfig

#install gitohashi
git clone https://xxx/gitohashi-orig.git && cd gitohashi-orig && mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig

#create git user
sudo useradd -rmUs /bin/bash git && sudo groupmod -g 48 git && sudo usermod -u 48 git && sudo su git && usermod -aG sudo git && ssh-keygen

#install gitolite3
#copy ssh pub-key from /home/git/.ssh/id_rsa.pub (whole file)
sudo apt install gitolite3

#add gitohashi to system
sudo cp -rp ./etc-gitohashi /etc/gitohashi
# change repo-base-dir value to "/var/lib/gitolite3/repositories"
sudo cp /usr/local/lib/systemd/system/gitohashi.service /lib/systemd/system/

#start
sudo gitohashi
```
Appreciate any guide, Milad

**Comment by lws-team** [comment]
selinux?  Have a look in your journal

**Comment by MNR85** [comment]
I used debian 10.
instead of journal, I executed
```
sudo gitohashi
```
for starting service manually. and the error I sent was part of it. Here is full log
```
sudo gitohashi 
[sudo] password for mikado: 
Gitohashi - Copyright (C) 2018 Andy Green <andy@warmcat.com>
Using config dir: "/etc/gitohashi"
LWS: 4.1.99-v4.1.0-209-gd5fe49fe, loglevel 1031
NET CLI SRV H1 H2 WS IPv6-absent
 ++ [wsi|0|pipe] (1)
 ++ [vh|0|netlink] (1)
  + extra-mimetypes .zip -> application/zip
  + extra-mimetypes .map -> application/json
  + extra-mimetypes .ttf -> application/x-font-ttf
  adding header content-security-policy=default-src 'none'; img-src 'self' data: https://travis-ci.org https://api.travis-ci.org https://ci.appveyor.com https://scan.coverity.com; script-src 'self'; font-src 'self'; style-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none';
  adding header x-content-type-options=nosniff
  adding header x-xss-protection=1; mode=block
  adding header x-frame-options=deny
  adding header referrer-policy=no-referrer
 ++ [vh|1|localhost||443] (2)
 SSL ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:!SHA1:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES128-SHA256:!AES128-GCM-SHA256:!AES128-SHA256:!DHE-RSA-AES256-SHA256:!AES256-GCM-SHA384:!AES256-SHA256'
 Vhost 'localhost' using TLS mode
 ++ [wsi|1|listen|localhost||443] (2)
  adding header content-security-policy=default-src 'none'; img-src 'self' data: https://travis-ci.org https://api.travis-ci.org https://ci.appveyor.com https://scan.coverity.com; script-src 'self'; font-src 'self'; style-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none';
  adding header x-content-type-options=nosniff
  adding header x-xss-protection=1; mode=block
  adding header x-frame-options=deny
  adding header referrer-policy=no-referrer
 ++ [vh|2|unixskt|/var/run/gitohas] (3)
 Vhost 'unixskt' using non-TLS mode
lws_socket_bind: vh unixskt unix skt /var/run/gitohashi-unixskt perms 48:48
 ++ [wsi|2|listen|unixskt|/var/run] (3)
jg2_gitolite3_interface
gl3 if running as uid 109 / gid 114 on pid 4384
jg2_gitolite3_interface: query result 0
jg2_gitolite3_blocking_query: query result 0
jg2_gitolite3_interface: read 3, v3
jg2_vhost_create: created gl3 interface, detected v3
lws_plat_drop_app_privileges: effective group 'git'
lws_plat_drop_app_privileges: effective user 'git'
   vhost localhost: cert expiry: 729423d
 ++ [wsisrv|0|adopted] (1)
 -- [wsisrv|0|adopted] (0)    21.979ms 
 ++ [wsisrv|1|adopted] (1)
 ++ [wsisrv|2|h2] (2)
__jg2_conf_gitolite_admin_head: can't open /var/lib/gitolite3/repositories/gitolite-admin.git
 -- [wsisrv|2|h2] (1)   754us     
lwsac_use_cached_file_end: html refcount zero on entry
 ++ [wsisrv|3|h2] (2)
 ++ [wsisrv|4|h2] (3)
 -- [wsisrv|4|h2] (2)   514us     
 ++ [wsisrv|5|h2] (3)
 ++ [wsisrv|6|h2] (4)
 ++ [wsisrv|7|h2] (5)
 ++ [wsisrv|8|h2] (6)
 ++ [wsisrv|9|h2] (7)
 -- [wsisrv|7|h2] (6)   302us     
 -- [wsisrv|6|h2] (5)   344us     
 -- [wsisrv|3|h2] (4)    19.851ms 
 -- [wsisrv|8|h2] (3)    23.976ms 
 -- [wsisrv|9|h2] (2)    45.684ms 
 -- [wsisrv|5|h2] (1)   139.049ms 
 ++ [wsisrv|a|h2] (2)
 -- [wsisrv|a|h2] (1)   472us     
 -- [wsisrv|1|adopted] (0)     5.587s
```

**Comment by lws-team** [comment]
... if your kernel has selinux, it will log violations somewhere... if systemd, you can use, eg, sudo journalctl -fan 200 to see the last 200 lines and "follow" new logs until you hit ^C.  If not systemd, it will be in /var/log/messages or so and you can see it with tail -f.

**Comment by MNR85** [comment]
I used two system. A container with debian 10, and a pc with ubuntu 20.04. SELinux is disabled on both. On my container I cant use systemctl because I dont have systemd.
On my pc, I started service with this command
```
systemctl start gitohashi
```
And I check journal for log, no error found and I could use service. Everything seems OK. But if I start service with this command  (still on my PC)( I used binary address in gitohashi.service file, and there was no input args)
```
sudo /usr/local/bin/gitohashi
```
I have the same error as before
```
__jg2_conf_gitolite_admin_head: can't open /var/lib/gitolite3/repositories/gitolite-admin.git
```
(There is a different between systemctl start and binary execution)
I checked /var/log, and last edited files were
```
syslog
auth.log
kern.log
```
but couldnt find any info related to gitohashi. So log is as my last comment.(https://github.com/warmcat/gitohashi/issues/2#issuecomment-762659284)
How we can use gitohashi with binary file?

**Comment by lws-team** [comment]
We should maybe back up to basics a bit... because I assume you know what you are doing and meet some problem with gitohashi, but maybe something earlier is wrong.

Have you installed gitolite on your box?

Has you configured gitolite and put at least one repo in it?

Does a file at that path (`/var/lib/gitolite3/repositories/gitolite-admin.git`) even exist?  It's the path to your gitolite admin repo, where it can find a copy of the gitolite access permissions, you may call your gitolite admin repo something else.

**Comment by MNR85** [comment]
I'm starting to work with gitohashi. But as I mentioned before, yes I installed gitolite3 and I have that path on my system. And gitolite created a testing.git repo for me.
```
/var/lib/gitolite3/repositories$ ls
gitolite-admin.git  testing.git
```
And I changed repo-base-dir in gitohashi to this folder.
After this error I even changed the permission of folder to +777. but no effect. 
With this ```systemctl start gitohashi``` everything seems ok. with ```sudo /usr/local/bin/gitohashi``` there was that error. So maybe we can consider we have all packages installed.

**Comment by lws-team** [comment]
Can the user that gitohashi is running under actually get into /var/lib/gitolite3, before the file permissions itself?

On my setup, the repo base is like this

```
"repo-base-dir": "/srv/gitolite/repositories",
```

I set it to run in the same uid/gis as lwsws on my system

```
   "uid": "48", # after init, run as apache user
   "gid": "48", # after init, run as apache group
```

Then I make sure that `/srv/gitolite` can be read by apache (the gitohashi group)

```
$ ls -l /srv
drwxr-x---  8 git  apache  4096 Dec  5 08:59 gitolite
```

and the same for `/src/gitolite/repositories`

```
$ ls -l /srv/gitolite/repositories
drwxrws---+ 53 git  apache 4096 Dec  5 06:01 repositories
```

You have to do some additional magic to make sure these permissions propagate to new files when you push them to gitolite, it's written up somewhere in the READMEs.

If you run gitohashi by hand with sudo, there is a quirk, you may need to set HOME for the process, from the top level README.md

```
Notes on developing with gitohashi

    You can run gitohashi from the commandline with sudo, but you must
    override HOME. libgit2 will try to use any .gitrc in your original user's
    HOME and fail on opening the repos. Use this kind of thing:

$ sudo HOME=/tmp valgrind --leak-check=full --show-leak-kinds=all /usr/local/bin/gitohashi
```

**Comment by MNR85** [comment]
Thank you. Yes There was two problem that needed attention
1- gitolite user should have access to repo-base-dir
2- run sudo with that magic command to override HOME, that I missed in readme 
Best regards, Milad
