### ISSUE TITLE
access control problem

### ISSUE THREAD

**Issue by MNR85** [warmcat/gitohashi#3]
Hi. I managed to run a gitohashi server.
For managing users and repos I used https://gitolite.com/gitolite/basic-admin.html and managed to create some repo with different accesses. When I use git commands everything is OK and accesses are correct ( .i.e git clone xxx ), but
If I use browser to show a repo ( or http get that url ) that only a specific user has access over it ( url like https://git-server-xxx.local/git/somerepo) I have access to see it! Actually you can see all repos with changing url to fit that repo name, and no acl matters here!
It seems that there is a missing link between gitolite and libgit2. How should I fix this?
With regards, Milad

**Comment by lws-team** [comment]
Well found... I only tested the acls for generating the vhost repolist page, it's works well for that.

But as you say it will allow things for display on the wrong vhost if you have the right url.

I pushed a fix that makes it hang up if no acl.

**Comment by lws-team** [comment]
The patch solves what you were seeing?

**Comment by MNR85** [comment]
Thanks for fast fixing. I will inform you after checking

**Comment by MNR85** [comment]
Yes the problem was solved. Thank u
